Put +
Log "Suite-Version-3"
Put +
"ApplicationUtils/InitialSetup".LaunchNopCommerce
"ApplicationUtils/HomeScreen".ComputersMenu "Notebooks"
"ApplicationUtils/HomeScreen".SelectAnyProduct "Asus Laptop"
"ApplicationUtils/HomeScreen".AddToCart
"ApplicationUtils/HomeScreen".VerifySuccessMessageOfProductAddingToCart
"ApplicationUtils/HomeScreen".SelectShoppingCart
"BrowserUtils/ChromeUtils".TerminateAllWindows

